import React,{useEffect,useMemo,useRef,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {Search,ChevronDown} from "lucide-react";
import {products,categories} from "../data/products";
import {useStore} from "../context";
import ProductGrid from "../components/ProductGrid";
export default function Shop(){
 const {lang}=useStore(); const t=lang==="ar"; const [params]=useSearchParams(); const initial=params.get("category")||"All";
 const [q,setQ]=useState(""); const [cat,setCat]=useState(initial); const [sort,setSort]=useState("featured"); const [max,setMax]=useState(100); const [showAll,setShowAll]=useState(false);
 const itemsRef=useRef(null);
 const list=useMemo(()=>{let a=products.filter(p=>(cat==="All"||p.category===cat)&&p.price<=max&&(p.name.toLowerCase().includes(q.toLowerCase())||p.nameAr.includes(q)));if(sort==="low")a.sort((x,y)=>x.price-y.price);if(sort==="high")a.sort((x,y)=>y.price-x.price);if(sort==="rating")a.sort((x,y)=>y.rating-x.rating);return a},[q,cat,sort,max]);
 useEffect(()=>{setCat(initial);setShowAll(false);},[initial]);
 const scrollToItems=()=>{setTimeout(()=>itemsRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),50)};
 const changeCategory=(value)=>{setCat(value);setShowAll(false);scrollToItems()};
 const changeSearch=(value)=>{setQ(value);setShowAll(false);scrollToItems()};
 const visible=showAll?list:list.slice(0,16);
 return <main className="container-x py-12"><div className="mb-10"><div className="text-brand-600 text-xs font-extrabold tracking-[.18em] uppercase">{t?"القائمة":"The menu"}</div><h1 className="text-4xl md:text-5xl font-black mt-2">{t?"قائمة الطعام":"Our menu"}</h1><p className="text-slate-500 mt-3">{t?"أطباق طازجة، مشاوي، أطباق سعودية وحلويات.":"Freshly prepared starters, grills, mains, desserts and drinks."}</p></div>
 <div className="grid lg:grid-cols-[240px_1fr] gap-8"><aside className="bg-white rounded-2xl border border-[#eadfce] p-5 h-fit lg:sticky lg:top-28"><div className="flex items-center justify-between mb-5"><b>{t?"التصفية":"Filter"}</b><button onClick={()=>{setCat("All");setMax(100);setQ("");setShowAll(false);scrollToItems()}} className="text-xs text-brand-600">{t?"مسح":"Clear"}</button></div><label className="text-xs font-bold text-slate-500">{t?"القسم":"Category"}</label><div className="grid gap-1 mt-2">{[["All",t?"الكل":"All"],...categories.map(c=>[c.name,t?c.nameAr:c.name])].map(([v,l])=><button key={v} onClick={()=>changeCategory(v)} className={`text-start px-3 py-2.5 rounded-xl text-sm ${cat===v?"bg-brand-50 text-brand-700 font-bold":"text-slate-600 hover:bg-slate-50"}`}>{l}</button>)}</div><label className="text-xs font-bold text-slate-500 block mt-6">{t?"أقصى سعر":"Maximum price"}: {max} SAR</label><input type="range" min="10" max="100" value={max} onChange={e=>{setMax(+e.target.value);setShowAll(false);scrollToItems()}} className="w-full mt-3 accent-[#b4532a]"/></aside>
 <section ref={itemsRef} id="menu-items" className="scroll-mt-28"><div className="flex flex-col sm:flex-row gap-3 mb-6"><div className="relative flex-1"><Search className="absolute start-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={q} onChange={e=>changeSearch(e.target.value)} placeholder={t?"ابحث في القائمة...":"Search the menu..."} className="w-full bg-white border border-slate-200 rounded-xl py-3.5 ps-11 pe-4 outline-none focus:border-brand-500"/></div><select value={sort} onChange={e=>{setSort(e.target.value);setShowAll(false);scrollToItems()}} className="bg-white border border-slate-200 rounded-xl px-4 py-3.5 outline-none"><option value="featured">{t?"المميز":"Featured"}</option><option value="low">{t?"السعر: الأقل":"Price: low to high"}</option><option value="high">{t?"السعر: الأعلى":"Price: high to low"}</option><option value="rating">{t?"الأعلى تقييماً":"Top rated"}</option></select></div><div className="text-xs text-slate-400 mb-5">{list.length} {t?"طبق":"items"}</div>{list.length?<><ProductGrid products={visible}/>{list.length>16&&!showAll&&<div className="flex justify-center mt-10"><button onClick={()=>setShowAll(true)} className="inline-flex items-center gap-2 bg-[#3b2417] text-white px-7 py-3.5 rounded-full font-bold hover:opacity-90 transition">{t?"عرض جميع الأطباق":"View all items"}<ChevronDown size={18}/></button></div>}{showAll&&list.length>16&&<div className="flex justify-center mt-8"><button onClick={()=>{setShowAll(false);scrollToItems()}} className="text-sm font-bold text-brand-700">{t?"عرض أقل":"Show less"}</button></div>}</>:<div className="py-20 text-center bg-white rounded-2xl">{t?"لم يتم العثور على أطباق.":"No dishes found."}</div>}</section></div></main>
}
